# Auto-generated by Terraform — do not edit manually
# Instance: ${instance_id}

[webservers]
${public_ip} ansible_user=${ansible_user} ansible_port=22 ansible_host=${public_ip}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
deploy_env=production
instance_id=${instance_id}
private_ip=${private_ip}
